# Generated by Django 5.2.16 on 2026-09-26 15:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_initial'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerteStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('synchronise', models.BooleanField(default=False)),
                ('supprime', models.BooleanField(default=False)),
                ('date_synchronisation', models.DateTimeField(blank=True, null=True)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motif', models.CharField(choices=[('perime', 'Périmé'), ('abime', 'Abîmé / cassé'), ('vol', 'Vol / disparu'), ('don', 'Don'), ('consommation', 'Consommation interne'), ('autre', 'Autre')], max_length=20)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('valeur', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pertes', to='stock.depot')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.variante')),
            ],
            options={
                'ordering': ['-date_creation'],
                'abstract': False,
            },
        ),
    ]
