# Generated by Django 5.2.16 on 2026-09-27 03:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0008_boutique_synchro_autorisee'),
        ('stock', '0004_operationdestockage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleveDormants',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('synchronise', models.BooleanField(default=False)),
                ('supprime', models.BooleanField(default=False)),
                ('date_synchronisation', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('jours_seuil', models.PositiveIntegerField(default=60)),
                ('nombre_articles', models.PositiveIntegerField(default=0)),
                ('valeur_immobilisee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releves_dormants', to='comptes.boutique')),
            ],
            options={
                'ordering': ['-date_creation'],
                'abstract': False,
            },
        ),
    ]
