# Generated by Django 5.2.16 on 2026-09-27 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_relevedormants'),
    ]

    operations = [
        migrations.AddField(
            model_name='pertestock',
            name='annulee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pertestock',
            name='date_annulation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
