# Generated by Django 5.2.16 on 2026-09-29 12:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_variante_quantite_detail_variante_variante_detail'),
        ('stock', '0006_perte_annulation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Detaillage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('synchronise', models.BooleanField(default=False)),
                ('supprime', models.BooleanField(default=False)),
                ('date_synchronisation', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('detailler', 'Déballer'), ('regrouper', 'Remballer')], max_length=20)),
                ('quantite_source', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantite_cible', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cout_unitaire_cible', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('annulee', models.BooleanField(default=False)),
                ('date_annulation', models.DateTimeField(blank=True, null=True)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detaillages', to='stock.depot')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('variante_cible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detaillages_cible', to='catalogue.variante')),
                ('variante_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detaillages_source', to='catalogue.variante')),
            ],
            options={
                'ordering': ['-date_creation'],
                'abstract': False,
            },
        ),
    ]
