# Generated by Django 5.2.16 on 2026-07-26 17:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionMobileMoney',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('synchronise', models.BooleanField(default=False)),
                ('supprime', models.BooleanField(default=False)),
                ('date_synchronisation', models.DateTimeField(blank=True, null=True)),
                ('fournisseur', models.CharField(choices=[('wave', 'Wave'), ('orange_money', 'Orange Money'), ('mtn', 'MTN Mobile Money')], max_length=20)),
                ('numero_telephone', models.CharField(max_length=30)),
                ('reference_externe', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('reussie', 'Réussie'), ('echouee', 'Échouée')], default='en_attente', max_length=15)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('donnees_brutes', models.JSONField(blank=True, default=dict)),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_mobile_money', to='ventes.paiement')),
            ],
            options={
                'ordering': ['-date_creation'],
                'abstract': False,
            },
        ),
    ]
