# Generated by Django 5.2.16 on 2026-07-26 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('achats', '0001_initial'),
        ('catalogue', '0001_initial'),
        ('comptes', '0001_initial'),
        ('fournisseurs', '0001_initial'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeachat',
            name='boutique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_achat', to='comptes.boutique'),
        ),
        migrations.AddField(
            model_name='commandeachat',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='fournisseurs.fournisseur'),
        ),
        migrations.AddField(
            model_name='commandeachat',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ligneachat',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='achats.commandeachat'),
        ),
        migrations.AddField(
            model_name='ligneachat',
            name='variante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.variante'),
        ),
        migrations.AddField(
            model_name='reception',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptions', to='achats.commandeachat'),
        ),
        migrations.AddField(
            model_name='reception',
            name='depot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.depot'),
        ),
        migrations.AddField(
            model_name='reception',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
