# Generated by Django 5.2.16 on 2026-09-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneachat',
            name='quantite_recue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
