# Generated by Django 5.2.16 on 2026-09-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0003_ligneachat_quantite_recue'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='reception',
            name='valeur_recue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
