# Generated by Django 5.2.16 on 2026-09-27 03:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0004_reception_montant_paye_reception_valeur_recue'),
        ('catalogue', '0002_initial'),
        ('stock', '0006_perte_annulation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='annulee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reception',
            name='date_annulation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RetourFournisseur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('synchronise', models.BooleanField(default=False)),
                ('supprime', models.BooleanField(default=False)),
                ('date_synchronisation', models.DateTimeField(blank=True, null=True)),
                ('motif', models.CharField(blank=True, max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('avoir', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retours', to='achats.commandeachat')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.depot')),
                ('reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retours', to='achats.reception')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LigneRetourFournisseur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('synchronise', models.BooleanField(default=False)),
                ('supprime', models.BooleanField(default=False)),
                ('date_synchronisation', models.DateTimeField(blank=True, null=True)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sous_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.variante')),
                ('retour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='achats.retourfournisseur')),
            ],
            options={
                'ordering': ['-date_creation'],
                'abstract': False,
            },
        ),
    ]
