# Generated by Django 5.2.16 on 2026-09-27 14:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0005_reception_annulee_reception_date_annulation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvenementCommande',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('synchronise', models.BooleanField(default=False)),
                ('supprime', models.BooleanField(default=False)),
                ('date_synchronisation', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('creee', 'Créée'), ('modifiee', 'Modifiée'), ('commandee', 'Passée en commandée'), ('reception', 'Réception'), ('reception_annulee', 'Réception annulée'), ('retour', 'Retour fournisseur'), ('paiement', 'Paiement'), ('annulee', 'Annulée')], max_length=20)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='achats.commandeachat')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_creation'],
            },
        ),
    ]
