# Generated by Django 5.2.16 on 2026-09-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0006_evenementcommande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenementcommande',
            name='type',
            field=models.CharField(choices=[('creee', 'Créée'), ('modifiee', 'Modifiée'), ('commandee', 'Passée en commandée'), ('reception', 'Réception'), ('reception_annulee', 'Réception annulée'), ('retour', 'Retour fournisseur'), ('paiement', 'Paiement'), ('paiement_annule', 'Paiement annulé'), ('annulee', 'Annulée')], max_length=20),
        ),
    ]
