# Generated by Django 5.2.16 on 2026-09-30 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0007_alter_evenementcommande_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='mode_paiement',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='reception',
            name='operateur_paiement',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
