# Generated by Django 5.2.16 on 2026-07-26 10:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('clients', '0001_initial'),
        ('comptes', '0001_initial'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('synchronise', models.BooleanField(default=False)),
                ('supprime', models.BooleanField(default=False)),
                ('date_synchronisation', models.DateTimeField(blank=True, null=True)),
                ('numero', models.CharField(blank=True, max_length=50)),
                ('total_brut', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('statut', models.CharField(choices=[('payee', 'Payée'), ('credit', 'À crédit'), ('annulee', 'Annulée')], default='payee', max_length=15)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='comptes.boutique')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to='clients.client')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to='stock.depot')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('synchronise', models.BooleanField(default=False)),
                ('supprime', models.BooleanField(default=False)),
                ('date_synchronisation', models.DateTimeField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('especes', 'Espèces'), ('mobile_money', 'Mobile Money'), ('carte', 'Carte'), ('credit', 'Crédit')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='ventes.vente')),
            ],
            options={
                'ordering': ['-date_creation'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LigneVente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('synchronise', models.BooleanField(default=False)),
                ('supprime', models.BooleanField(default=False)),
                ('date_synchronisation', models.DateTimeField(blank=True, null=True)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cout_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sous_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.variante')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='ventes.vente')),
            ],
            options={
                'ordering': ['-date_creation'],
                'abstract': False,
            },
        ),
    ]
