# Generated by Django 5.2.16 on 2026-08-06 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='operateur',
            field=models.CharField(blank=True, choices=[('orange_money', 'Orange Money'), ('mtn_money', 'MTN Money'), ('moov_money', 'Moov Money'), ('wave', 'Wave')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='mode',
            field=models.CharField(choices=[('especes', 'Espèces'), ('mobile_money', 'Mobile Money'), ('credit', 'Crédit')], max_length=20),
        ),
    ]
