# Generated by Django 5.2.16 on 2026-09-26 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_destockage'),
        ('ventes', '0002_paiement_operateur_alter_paiement_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignevente',
            name='destockage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_vente', to='stock.destockage'),
        ),
        migrations.AddField(
            model_name='lignevente',
            name='prix_normal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
