# Generated by Django 5.2.16 on 2026-09-30 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0003_lignevente_destockage_lignevente_prix_normal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='mode',
            field=models.CharField(choices=[('especes', 'Espèces'), ('mobile_money', 'Mobile Money'), ('credit', 'Crédit'), ('compte_client', 'Compte client')], max_length=20),
        ),
    ]
