# Generated by Django 5.2.16 on 2026-10-01 13:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_variante_quantite_detail_variante_variante_detail'),
        ('clients', '0006_mouvementcompteclient'),
        ('comptes', '0008_boutique_synchro_autorisee'),
        ('stock', '0007_detaillage'),
        ('ventes', '0004_alter_paiement_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('synchronise', models.BooleanField(default=False)),
                ('supprime', models.BooleanField(default=False)),
                ('date_synchronisation', models.DateTimeField(blank=True, null=True)),
                ('numero', models.CharField(blank=True, max_length=50)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('prete', 'Prête'), ('partielle', 'Livrée en partie'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=15)),
                ('date_livraison_prevue', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('avance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_annulation', models.DateTimeField(blank=True, null=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_client', to='comptes.boutique')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='clients.client')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes_client', to='stock.depot')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='vente',
            name='commande_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons', to='ventes.commandeclient'),
        ),
        migrations.CreateModel(
            name='LigneCommandeClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('synchronise', models.BooleanField(default=False)),
                ('supprime', models.BooleanField(default=False)),
                ('date_synchronisation', models.DateTimeField(blank=True, null=True)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantite_livree', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sous_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='ventes.commandeclient')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogue.variante')),
            ],
            options={
                'ordering': ['-date_creation'],
                'abstract': False,
            },
        ),
    ]
