/**
 * Port TypeScript de comptabilite/plan_comptable.py : jeu de comptes
 * SYSCOHADA (Système Normal) standard, classes 1 à 9. Utilisé uniquement
 * pour l'aperçu comptable local (voir services/comptabilite.ts) — pas une
 * reproduction officielle exhaustive de l'annexe du texte, à faire relire
 * par un comptable avant tout usage fiscal réel.
 */

export interface CompteSyscohada {
  numero: string;
  libelle: string;
  classe: number;
}

export const PLAN_COMPTABLE_SYSCOHADA: CompteSyscohada[] = [
  { numero: "10", libelle: "Capital", classe: 1 },
  { numero: "101", libelle: "Capital social", classe: 1 },
  { numero: "104", libelle: "Primes liées au capital social", classe: 1 },
  { numero: "105", libelle: "Écarts de réévaluation", classe: 1 },
  { numero: "106", libelle: "Réserves", classe: 1 },
  { numero: "1061", libelle: "Réserve légale", classe: 1 },
  { numero: "1063", libelle: "Réserves statutaires", classe: 1 },
  { numero: "1068", libelle: "Autres réserves", classe: 1 },
  { numero: "109", libelle: "Actionnaires, capital souscrit non appelé", classe: 1 },
  { numero: "11", libelle: "Report à nouveau", classe: 1 },
  { numero: "110", libelle: "Report à nouveau créditeur", classe: 1 },
  { numero: "119", libelle: "Report à nouveau débiteur", classe: 1 },
  { numero: "12", libelle: "Résultat net de l'exercice", classe: 1 },
  { numero: "120", libelle: "Résultat net : bénéfice", classe: 1 },
  { numero: "129", libelle: "Résultat net : perte", classe: 1 },
  { numero: "14", libelle: "Subventions d'investissement", classe: 1 },
  { numero: "141", libelle: "Subventions d'équipement", classe: 1 },
  { numero: "16", libelle: "Emprunts et dettes assimilées", classe: 1 },
  { numero: "161", libelle: "Emprunts obligataires", classe: 1 },
  { numero: "162", libelle: "Emprunts auprès des établissements de crédit", classe: 1 },
  { numero: "166", libelle: "Intérêts courus", classe: 1 },
  { numero: "17", libelle: "Dettes de crédit-bail et contrats assimilés", classe: 1 },
  { numero: "19", libelle: "Provisions financières pour risques et charges", classe: 1 },
  { numero: "191", libelle: "Provisions pour litiges", classe: 1 },
  { numero: "194", libelle: "Provisions pour charges à répartir", classe: 1 },
  { numero: "20", libelle: "Charges immobilisées", classe: 2 },
  { numero: "201", libelle: "Frais de développement et de prospection", classe: 2 },
  { numero: "21", libelle: "Immobilisations incorporelles", classe: 2 },
  { numero: "211", libelle: "Frais de recherche et de développement", classe: 2 },
  { numero: "212", libelle: "Brevets, licences, concessions et droits similaires", classe: 2 },
  { numero: "213", libelle: "Logiciels", classe: 2 },
  { numero: "214", libelle: "Fonds commercial", classe: 2 },
  { numero: "22", libelle: "Terrains", classe: 2 },
  { numero: "221", libelle: "Terrains agricoles et forestiers", classe: 2 },
  { numero: "222", libelle: "Terrains bâtis", classe: 2 },
  { numero: "23", libelle: "Bâtiments, installations techniques et agencements", classe: 2 },
  { numero: "231", libelle: "Bâtiments industriels, agricoles et commerciaux", classe: 2 },
  { numero: "233", libelle: "Ouvrages d'infrastructure", classe: 2 },
  { numero: "234", libelle: "Installations techniques", classe: 2 },
  { numero: "238", libelle: "Autres installations et agencements", classe: 2 },
  { numero: "24", libelle: "Matériel, mobilier et actifs biologiques", classe: 2 },
  { numero: "241", libelle: "Matériel et outillage industriel et commercial", classe: 2 },
  { numero: "2441", libelle: "Matériel de bureau", classe: 2 },
  { numero: "2442", libelle: "Matériel informatique", classe: 2 },
  { numero: "2444", libelle: "Mobilier de bureau", classe: 2 },
  { numero: "245", libelle: "Matériel de transport", classe: 2 },
  { numero: "25", libelle: "Avances et acomptes versés sur immobilisations", classe: 2 },
  { numero: "26", libelle: "Titres de participation", classe: 2 },
  { numero: "27", libelle: "Autres immobilisations financières", classe: 2 },
  { numero: "275", libelle: "Dépôts et cautionnements versés", classe: 2 },
  { numero: "28", libelle: "Amortissements", classe: 2 },
  { numero: "2813", libelle: "Amortissements des logiciels", classe: 2 },
  { numero: "2831", libelle: "Amortissements des bâtiments", classe: 2 },
  { numero: "2841", libelle: "Amortissements du matériel et outillage", classe: 2 },
  { numero: "2845", libelle: "Amortissements du matériel de transport", classe: 2 },
  { numero: "29", libelle: "Provisions pour dépréciation des immobilisations", classe: 2 },
  { numero: "31", libelle: "Marchandises", classe: 3 },
  { numero: "311", libelle: "Marchandises A", classe: 3 },
  { numero: "32", libelle: "Matières premières et fournitures liées", classe: 3 },
  { numero: "33", libelle: "Autres approvisionnements", classe: 3 },
  { numero: "36", libelle: "Produits finis", classe: 3 },
  { numero: "37", libelle: "Stocks provenant d'immobilisations", classe: 3 },
  { numero: "38", libelle: "Stocks en cours de route, en consignation ou en dépôt", classe: 3 },
  { numero: "39", libelle: "Dépréciations des stocks", classe: 3 },
  { numero: "40", libelle: "Fournisseurs et comptes rattachés", classe: 4 },
  { numero: "401", libelle: "Fournisseurs, dettes en compte", classe: 4 },
  { numero: "408", libelle: "Fournisseurs, factures non parvenues", classe: 4 },
  { numero: "409", libelle: "Fournisseurs débiteurs (avances et acomptes versés)", classe: 4 },
  { numero: "41", libelle: "Clients et comptes rattachés", classe: 4 },
  { numero: "411", libelle: "Clients", classe: 4 },
  { numero: "416", libelle: "Clients douteux ou litigieux", classe: 4 },
  { numero: "418", libelle: "Clients, produits non encore facturés", classe: 4 },
  { numero: "419", libelle: "Clients créditeurs (avances et acomptes reçus)", classe: 4 },
  { numero: "42", libelle: "Personnel", classe: 4 },
  { numero: "421", libelle: "Personnel, avances et acomptes", classe: 4 },
  { numero: "422", libelle: "Personnel, rémunérations dues", classe: 4 },
  { numero: "43", libelle: "Organismes sociaux", classe: 4 },
  { numero: "431", libelle: "Sécurité sociale", classe: 4 },
  { numero: "44", libelle: "État et collectivités publiques", classe: 4 },
  { numero: "441", libelle: "État, impôt sur les bénéfices", classe: 4 },
  { numero: "443", libelle: "État, TVA facturée", classe: 4 },
  { numero: "4431", libelle: "TVA facturée sur ventes", classe: 4 },
  { numero: "445", libelle: "État, TVA récupérable", classe: 4 },
  { numero: "4452", libelle: "TVA récupérable sur achats", classe: 4 },
  { numero: "447", libelle: "État, impôts retenus à la source", classe: 4 },
  { numero: "4472", libelle: "Impôts et taxes recouvrables sur des tiers", classe: 4 },
  { numero: "45", libelle: "Organismes internationaux", classe: 4 },
  { numero: "46", libelle: "Associés et groupe", classe: 4 },
  { numero: "47", libelle: "Débiteurs et créditeurs divers", classe: 4 },
  { numero: "470", libelle: "Débiteurs divers", classe: 4 },
  { numero: "471", libelle: "Créditeurs divers", classe: 4 },
  { numero: "476", libelle: "Différences de conversion, actif", classe: 4 },
  { numero: "477", libelle: "Différences de conversion, passif", classe: 4 },
  { numero: "48", libelle: "Créances et dettes hors activités ordinaires (HAO)", classe: 4 },
  { numero: "481", libelle: "Fournisseurs d'investissements", classe: 4 },
  { numero: "485", libelle: "Créances sur cessions d'immobilisations", classe: 4 },
  { numero: "49", libelle: "Dépréciations et risques provisionnés (comptes de tiers)", classe: 4 },
  { numero: "491", libelle: "Dépréciations des comptes clients", classe: 4 },
  { numero: "50", libelle: "Titres de placement", classe: 5 },
  { numero: "51", libelle: "Valeurs à encaisser", classe: 5 },
  { numero: "511", libelle: "Effets à encaisser", classe: 5 },
  { numero: "512", libelle: "Chèques à encaisser", classe: 5 },
  { numero: "52", libelle: "Banques", classe: 5 },
  { numero: "521", libelle: "Banques locales", classe: 5 },
  { numero: "53", libelle: "Établissements financiers et assimilés", classe: 5 },
  { numero: "54", libelle: "Instruments de trésorerie", classe: 5 },
  { numero: "55", libelle: "Mobile money et instruments de paiement électronique", classe: 5 },
  { numero: "551", libelle: "Mobile Money Wave", classe: 5 },
  { numero: "552", libelle: "Mobile Money Orange Money", classe: 5 },
  { numero: "553", libelle: "Mobile Money MTN Money", classe: 5 },
  { numero: "554", libelle: "Mobile Money Moov Money", classe: 5 },
  { numero: "57", libelle: "Caisse", classe: 5 },
  { numero: "571", libelle: "Caisse siège social", classe: 5 },
  { numero: "58", libelle: "Virements internes de fonds", classe: 5 },
  { numero: "59", libelle: "Dépréciations et provisions pour risques à court terme", classe: 5 },
  { numero: "60", libelle: "Achats et variations de stocks", classe: 6 },
  { numero: "601", libelle: "Achats de marchandises", classe: 6 },
  { numero: "6031", libelle: "Variation des stocks de marchandises", classe: 6 },
  { numero: "604", libelle: "Achats stockés de matières et fournitures liées", classe: 6 },
  { numero: "605", libelle: "Autres achats", classe: 6 },
  { numero: "608", libelle: "Achats d'emballages", classe: 6 },
  { numero: "61", libelle: "Transports", classe: 6 },
  { numero: "611", libelle: "Transports sur achats", classe: 6 },
  { numero: "612", libelle: "Transports sur ventes", classe: 6 },
  { numero: "618", libelle: "Autres frais de transport", classe: 6 },
  { numero: "62", libelle: "Services extérieurs A", classe: 6 },
  { numero: "621", libelle: "Sous-traitance générale", classe: 6 },
  { numero: "622", libelle: "Locations et charges locatives", classe: 6 },
  { numero: "624", libelle: "Entretien, réparations et maintenance", classe: 6 },
  { numero: "625", libelle: "Primes d'assurance", classe: 6 },
  { numero: "626", libelle: "Études, recherches et documentation", classe: 6 },
  { numero: "628", libelle: "Frais de télécommunications", classe: 6 },
  { numero: "63", libelle: "Services extérieurs B", classe: 6 },
  { numero: "631", libelle: "Frais bancaires", classe: 6 },
  { numero: "632", libelle: "Rémunérations d'intermédiaires et de conseils", classe: 6 },
  { numero: "633", libelle: "Frais de formation du personnel", classe: 6 },
  { numero: "637", libelle: "Rémunération de transfert de technologie", classe: 6 },
  { numero: "638", libelle: "Autres charges externes", classe: 6 },
  { numero: "64", libelle: "Impôts et taxes", classe: 6 },
  { numero: "641", libelle: "Impôts et taxes directs", classe: 6 },
  { numero: "645", libelle: "Impôts et taxes indirects", classe: 6 },
  { numero: "646", libelle: "Droits d'enregistrement", classe: 6 },
  { numero: "65", libelle: "Autres charges", classe: 6 },
  { numero: "658", libelle: "Charges diverses", classe: 6 },
  { numero: "66", libelle: "Charges de personnel", classe: 6 },
  { numero: "661", libelle: "Rémunérations directes versées au personnel national", classe: 6 },
  { numero: "663", libelle: "Indemnités forfaitaires versées au personnel", classe: 6 },
  { numero: "664", libelle: "Charges sociales", classe: 6 },
  { numero: "667", libelle: "Rémunération de l'exploitant individuel", classe: 6 },
  { numero: "67", libelle: "Frais financiers et charges assimilées", classe: 6 },
  { numero: "671", libelle: "Intérêts des emprunts", classe: 6 },
  { numero: "674", libelle: "Autres intérêts", classe: 6 },
  { numero: "676", libelle: "Pertes de change", classe: 6 },
  { numero: "68", libelle: "Dotations aux amortissements, provisions et dépréciations", classe: 6 },
  { numero: "681", libelle: "Dotations aux amortissements d'exploitation", classe: 6 },
  { numero: "691", libelle: "Dotations aux provisions d'exploitation", classe: 6 },
  { numero: "69", libelle: "Dotations aux provisions financières / HAO", classe: 6 },
  { numero: "70", libelle: "Ventes", classe: 7 },
  { numero: "701", libelle: "Ventes de marchandises", classe: 7 },
  { numero: "702", libelle: "Ventes de produits finis", classe: 7 },
  { numero: "706", libelle: "Services vendus", classe: 7 },
  { numero: "707", libelle: "Produits accessoires", classe: 7 },
  { numero: "71", libelle: "Subventions d'exploitation", classe: 7 },
  { numero: "72", libelle: "Production immobilisée", classe: 7 },
  { numero: "73", libelle: "Variations des stocks de biens et de services produits", classe: 7 },
  { numero: "75", libelle: "Autres produits", classe: 7 },
  { numero: "754", libelle: "Revenus des immeubles non affectés à l'exploitation", classe: 7 },
  { numero: "758", libelle: "Produits divers", classe: 7 },
  { numero: "77", libelle: "Revenus financiers et produits assimilés", classe: 7 },
  { numero: "771", libelle: "Intérêts de prêts", classe: 7 },
  { numero: "776", libelle: "Gains de change", classe: 7 },
  { numero: "78", libelle: "Transferts de charges", classe: 7 },
  { numero: "781", libelle: "Transferts de charges d'exploitation", classe: 7 },
  { numero: "79", libelle: "Reprises de provisions", classe: 7 },
  { numero: "81", libelle: "Valeurs comptables des cessions d'immobilisations", classe: 8 },
  { numero: "82", libelle: "Produits des cessions d'immobilisations", classe: 8 },
  { numero: "83", libelle: "Charges hors activités ordinaires", classe: 8 },
  { numero: "84", libelle: "Produits hors activités ordinaires", classe: 8 },
  { numero: "85", libelle: "Dotations HAO", classe: 8 },
  { numero: "86", libelle: "Reprises HAO", classe: 8 },
  { numero: "87", libelle: "Participation des travailleurs", classe: 8 },
  { numero: "88", libelle: "Subventions d'équilibre", classe: 8 },
  { numero: "89", libelle: "Impôts sur le résultat", classe: 8 },
  { numero: "90", libelle: "Engagements obtenus et accordés", classe: 9 },];

const PAR_NUMERO = new Map(PLAN_COMPTABLE_SYSCOHADA.map((c) => [c.numero, c]));

/** Résout un compte par numéro exact, sinon remonte vers le compte parent le plus proche. */
export function resoudreCompte(numero: string): CompteSyscohada {
  let recherche = numero;
  while (recherche) {
    const compte = PAR_NUMERO.get(recherche);
    if (compte) return compte;
    recherche = recherche.slice(0, -1);
  }
  return { numero, libelle: "Compte inconnu", classe: 0 };
}

