# Generated by Django 5.2.16 on 2026-07-26 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('comptes', '0001_initial'),
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='boutique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='comptes.boutique'),
        ),
        migrations.AddField(
            model_name='credit',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='clients.client'),
        ),
        migrations.AddField(
            model_name='credit',
            name='vente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventes.vente'),
        ),
        migrations.AddField(
            model_name='paiementcredit',
            name='credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='clients.credit'),
        ),
    ]
