# Generated by Django 5.2.16 on 2026-09-27 22:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_paiementcredit_utilisateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcheanceCredit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('synchronise', models.BooleanField(default=False)),
                ('supprime', models.BooleanField(default=False)),
                ('date_synchronisation', models.DateTimeField(blank=True, null=True)),
                ('date_echeance', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeances', to='clients.credit')),
            ],
            options={
                'ordering': ['date_echeance'],
            },
        ),
    ]
