# Generated by Django 5.2.16 on 2026-09-30 01:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_echeancecredit'),
        ('stock', '0007_detaillage'),
        ('ventes', '0004_alter_paiement_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementCompteClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('synchronise', models.BooleanField(default=False)),
                ('supprime', models.BooleanField(default=False)),
                ('date_synchronisation', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('depot', 'Dépôt'), ('utilisation', 'Utilisation'), ('rendu', 'Argent rendu'), ('annulation', 'Annulation (remis sur le compte)')], max_length=15)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mode', models.CharField(blank=True, default='', max_length=20)),
                ('operateur', models.CharField(blank=True, default='', max_length=20)),
                ('motif', models.CharField(blank=True, default='', max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_compte', to='clients.client')),
                ('credit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clients.credit')),
                ('depot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stock.depot')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ventes.vente')),
            ],
            options={
                'ordering': ['date_creation'],
            },
        ),
    ]
