# Generated by Django 5.2.16 on 2026-07-26 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribut',
            name='boutique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributs', to='comptes.boutique'),
        ),
        migrations.AddField(
            model_name='categorie',
            name='boutique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='comptes.boutique'),
        ),
        migrations.AddField(
            model_name='categorie',
            name='categorie_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_categories', to='catalogue.categorie'),
        ),
        migrations.AddField(
            model_name='produit',
            name='boutique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='comptes.boutique'),
        ),
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.categorie'),
        ),
        migrations.AddField(
            model_name='unite',
            name='boutique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unites', to='comptes.boutique'),
        ),
        migrations.AddField(
            model_name='produit',
            name='unite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.unite'),
        ),
        migrations.AddField(
            model_name='valeurattribut',
            name='attribut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valeurs', to='catalogue.attribut'),
        ),
        migrations.AddField(
            model_name='variante',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='catalogue.produit'),
        ),
        migrations.AddField(
            model_name='variantevaleur',
            name='valeur_attribut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.valeurattribut'),
        ),
        migrations.AddField(
            model_name='variantevaleur',
            name='variante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valeurs', to='catalogue.variante'),
        ),
        migrations.AlterUniqueTogether(
            name='variantevaleur',
            unique_together={('variante', 'valeur_attribut')},
        ),
    ]
