# Generated by Django 5.2.16 on 2026-07-26 10:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('achats', '0001_initial'),
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('synchronise', models.BooleanField(default=False)),
                ('supprime', models.BooleanField(default=False)),
                ('date_synchronisation', models.DateTimeField(blank=True, null=True)),
                ('nom', models.CharField(max_length=200)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('contact', models.CharField(blank=True, max_length=150)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fournisseurs', to='comptes.boutique')),
            ],
            options={
                'ordering': ['-date_creation'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetteFournisseur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('synchronise', models.BooleanField(default=False)),
                ('supprime', models.BooleanField(default=False)),
                ('date_synchronisation', models.DateTimeField(blank=True, null=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('solde', 'Soldé')], default='en_cours', max_length=15)),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='achats.commandeachat')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dettes', to='fournisseurs.fournisseur')),
            ],
            options={
                'ordering': ['-date_creation'],
                'abstract': False,
            },
        ),
    ]
