# Generated by Django 5.2.16 on 2026-09-27 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0005_reception_annulee_reception_date_annulation_and_more'),
        ('fournisseurs', '0002_paiementdettefournisseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='dettefournisseur',
            name='reception',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dettes', to='achats.reception'),
        ),
    ]
