# Generated by Django 5.2.16 on 2026-09-27 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0003_dettefournisseur_reception'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementdettefournisseur',
            name='annule_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paiementdettefournisseur',
            name='annulee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paiementdettefournisseur',
            name='date_annulation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiementdettefournisseur',
            name='motif_annulation',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
