# Generated by Django 5.2.16 on 2026-08-19 15:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0006_permissions_tresorerie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteComptable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('synchronise', models.BooleanField(default=False)),
                ('supprime', models.BooleanField(default=False)),
                ('date_synchronisation', models.DateTimeField(blank=True, null=True)),
                ('numero', models.CharField(max_length=8)),
                ('libelle', models.CharField(max_length=200)),
                ('classe', models.PositiveSmallIntegerField(choices=[(1, '1 — Comptes de ressources durables'), (2, "2 — Comptes d'actif immobilisé"), (3, '3 — Comptes de stocks'), (4, '4 — Comptes de tiers'), (5, '5 — Comptes de trésorerie'), (6, '6 — Comptes de charges des activités ordinaires'), (7, '7 — Comptes de produits des activités ordinaires'), (8, '8 — Comptes des autres charges et produits (HAO)'), (9, '9 — Engagements hors bilan / comptabilité analytique')])),
                ('actif', models.BooleanField(default=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes_comptables', to='comptes.boutique')),
                ('compte_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_comptes', to='comptabilite.comptecomptable')),
            ],
            options={
                'ordering': ['numero'],
                'unique_together': {('boutique', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='ExerciceComptable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('synchronise', models.BooleanField(default=False)),
                ('supprime', models.BooleanField(default=False)),
                ('date_synchronisation', models.DateTimeField(blank=True, null=True)),
                ('libelle', models.CharField(max_length=50)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('cloture', 'Clôturé')], default='ouvert', max_length=10)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercices_comptables', to='comptes.boutique')),
            ],
            options={
                'ordering': ['-date_debut'],
                'unique_together': {('boutique', 'libelle')},
            },
        ),
        migrations.CreateModel(
            name='JournalComptable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('synchronise', models.BooleanField(default=False)),
                ('supprime', models.BooleanField(default=False)),
                ('date_synchronisation', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(choices=[('CA', 'Journal de caisse'), ('BQ', 'Journal de banque'), ('AC', 'Journal des achats'), ('VE', 'Journal des ventes'), ('OD', 'Journal des opérations diverses')], max_length=5)),
                ('libelle', models.CharField(max_length=100)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journaux_comptables', to='comptes.boutique')),
            ],
            options={
                'unique_together': {('boutique', 'code')},
            },
        ),
        migrations.CreateModel(
            name='EcritureComptable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('synchronise', models.BooleanField(default=False)),
                ('supprime', models.BooleanField(default=False)),
                ('date_synchronisation', models.DateTimeField(blank=True, null=True)),
                ('numero', models.PositiveIntegerField()),
                ('date_ecriture', models.DateField()),
                ('libelle', models.CharField(max_length=255)),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('validee', 'Validée')], default='validee', max_length=10)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecritures_comptables', to='comptes.boutique')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecritures', to='comptabilite.exercicecomptable')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecritures', to='comptabilite.journalcomptable')),
            ],
            options={
                'ordering': ['-date_ecriture', '-numero'],
                'unique_together': {('exercice', 'journal', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='LigneEcriture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('synchronise', models.BooleanField(default=False)),
                ('supprime', models.BooleanField(default=False)),
                ('date_synchronisation', models.DateTimeField(blank=True, null=True)),
                ('libelle', models.CharField(blank=True, max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_ecriture', to='comptabilite.comptecomptable')),
                ('ecriture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='comptabilite.ecriturecomptable')),
            ],
            options={
                'ordering': ['-date_creation'],
                'abstract': False,
            },
        ),
    ]
