# Generated by Django 5.2.16 on 2026-08-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comptecomptable',
            name='classe',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 · Comptes de ressources durables'), (2, "2 · Comptes d'actif immobilisé"), (3, '3 · Comptes de stocks'), (4, '4 · Comptes de tiers'), (5, '5 · Comptes de trésorerie'), (6, '6 · Comptes de charges des activités ordinaires'), (7, '7 · Comptes de produits des activités ordinaires'), (8, '8 · Comptes des autres charges et produits (HAO)'), (9, '9 · Engagements hors bilan / comptabilité analytique')]),
        ),
    ]
