# Generated by Django 5.2.16 on 2026-07-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_utilisateur_depot'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='code_reinitialisation',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='code_reinitialisation_expire_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
