# Generated by Django 5.2.16 on 2026-07-30 22:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0003_utilisateur_code_reinitialisation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeInscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('synchronise', models.BooleanField(default=False)),
                ('supprime', models.BooleanField(default=False)),
                ('date_synchronisation', models.DateTimeField(blank=True, null=True)),
                ('boutique_nom', models.CharField(max_length=200)),
                ('boutique_adresse', models.CharField(blank=True, max_length=255)),
                ('boutique_telephone', models.CharField(blank=True, max_length=30)),
                ('boutique_email', models.EmailField(blank=True, max_length=254)),
                ('boutique_devise', models.CharField(default='FCFA', max_length=10)),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('mot_de_passe_hash', models.CharField(max_length=255)),
                ('formule', models.CharField(choices=[('essentiel', 'Essentiel'), ('pro', 'Pro')], default='essentiel', max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20)),
            ],
            options={
                'ordering': ['-date_creation'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='boutique',
            name='date_expiration_abonnement',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
