# Generated by Django 5.2.16 on 2026-07-31 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0004_demandeinscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='formule',
            field=models.CharField(choices=[('essentiel', 'Essentiel'), ('pro', 'Pro')], default='essentiel', max_length=20),
        ),
    ]
