# Generated by Django 5.2.16 on 2026-08-31 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0007_permission_comptabilite'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='synchro_autorisee',
            field=models.BooleanField(default=False),
        ),
    ]
