# Generated by Django 5.2.16 on 2026-10-02 18:50

from django.db import migrations, models

from comptes.codes_vendeur import calculer_code_vendeur


def attribuer_codes_existants(apps, schema_editor):
    """Donne un code vendeur à chaque compte déjà rattaché à une boutique."""
    Utilisateur = apps.get_model("comptes", "Utilisateur")
    pris_par_boutique = {}
    for utilisateur in Utilisateur.objects.exclude(boutique=None).order_by("date_joined", "id"):
        pris = pris_par_boutique.setdefault(utilisateur.boutique_id, set())
        utilisateur.code_vendeur = calculer_code_vendeur(
            utilisateur.first_name, utilisateur.last_name, utilisateur.username, pris
        )
        pris.add(utilisateur.code_vendeur)
        utilisateur.save(update_fields=["code_vendeur"])


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0008_boutique_synchro_autorisee'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='code_vendeur',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.RunPython(attribuer_codes_existants, migrations.RunPython.noop),
    ]
