# Generated by Django 5.2.16 on 2026-10-03 03:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def situation_de_depart(apps, schema_editor):
    """Première ligne du registre : l'abonnement en cours de chaque boutique."""
    Boutique = apps.get_model("comptes", "Boutique")
    PaiementAbonnement = apps.get_model("comptes", "PaiementAbonnement")
    for boutique in Boutique.objects.exclude(date_expiration_abonnement=None):
        PaiementAbonnement.objects.create(
            boutique=boutique,
            nature="ajustement",
            formule=boutique.formule,
            date_debut=boutique.date_creation,
            date_fin=boutique.date_expiration_abonnement,
            note="Abonnement en cours à l'ouverture du registre",
        )


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0009_code_vendeur'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglagesPlateforme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('synchronise', models.BooleanField(default=False)),
                ('supprime', models.BooleanField(default=False)),
                ('date_synchronisation', models.DateTimeField(blank=True, null=True)),
                ('numero_wave', models.CharField(blank=True, max_length=30)),
                ('numero_orange_money', models.CharField(blank=True, max_length=30)),
                ('numero_mtn', models.CharField(blank=True, max_length=30)),
                ('numero_moov', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('instructions', models.TextField(blank=True, help_text='Texte affiché au commerçant, ex. « Envoyez le montant puis la référence par WhatsApp ».')),
            ],
            options={
                'verbose_name': 'Réglages de la plateforme',
                'verbose_name_plural': 'Réglages de la plateforme',
            },
        ),
        migrations.CreateModel(
            name='PaiementAbonnement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('synchronise', models.BooleanField(default=False)),
                ('supprime', models.BooleanField(default=False)),
                ('date_synchronisation', models.DateTimeField(blank=True, null=True)),
                ('nature', models.CharField(choices=[('paiement', 'Paiement'), ('essai', 'Essai gratuit'), ('offert', 'Offert'), ('ajustement', 'Ajustement (correction de date)')], default='paiement', max_length=20)),
                ('formule', models.CharField(choices=[('essentiel', 'Essentiel'), ('pro', 'Pro')], max_length=20)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mode', models.CharField(blank=True, choices=[('wave', 'Wave'), ('orange_money', 'Orange Money'), ('mtn', 'MTN Mobile Money'), ('moov', 'Moov Money'), ('especes', 'Espèces'), ('banque', 'Banque'), ('autre', 'Autre')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_abonnement', to='comptes.boutique')),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='SignalementAbonnement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('synchronise', models.BooleanField(default=False)),
                ('supprime', models.BooleanField(default=False)),
                ('date_synchronisation', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('vente_hors_abonnement', "Vente après la fin de l'abonnement"), ('depot_hors_formule', 'Dépôt au-delà de la formule')], max_length=30)),
                ('table', models.CharField(max_length=60)),
                ('enregistrement_id', models.UUIDField()),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('traite', models.BooleanField(default=False)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements_abonnement', to='comptes.boutique')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.RunPython(situation_de_depart, migrations.RunPython.noop),
    ]
