# Generated by Django 5.2.16 on 2026-10-03 03:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0010_registre_abonnement'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeRenouvellement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('synchronise', models.BooleanField(default=False)),
                ('supprime', models.BooleanField(default=False)),
                ('date_synchronisation', models.DateTimeField(blank=True, null=True)),
                ('formule', models.CharField(choices=[('essentiel', 'Essentiel'), ('pro', 'Pro')], max_length=20)),
                ('duree_mois', models.PositiveSmallIntegerField(choices=[(1, '1 mois'), (3, '3 mois'), (6, '6 mois'), (12, '12 mois')])),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mode', models.CharField(choices=[('wave', 'Wave'), ('orange_money', 'Orange Money'), ('mtn', 'MTN Mobile Money'), ('moov', 'Moov Money'), ('especes', 'Espèces'), ('banque', 'Banque'), ('autre', 'Autre')], max_length=20)),
                ('reference', models.CharField(max_length=100)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20)),
                ('motif_rejet', models.CharField(blank=True, max_length=255)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_renouvellement', to='comptes.boutique')),
                ('demandeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('paiement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='comptes.paiementabonnement')),
                ('traitee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
