# Generated by Django 5.2.16 on 2026-10-03 03:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0011_demande_renouvellement'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglagesplateforme',
            name='prix_mensuel_essentiel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='reglagesplateforme',
            name='prix_mensuel_pro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='reglagesplateforme',
            name='remise_12_mois',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='remise sur 12 mois (%)'),
        ),
        migrations.AddField(
            model_name='reglagesplateforme',
            name='remise_3_mois',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='remise sur 3 mois (%)'),
        ),
        migrations.AddField(
            model_name='reglagesplateforme',
            name='remise_6_mois',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='remise sur 6 mois (%)'),
        ),
    ]
