# Generated by Django 5.2.16 on 2026-07-26 10:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalSync',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('synchronise', models.BooleanField(default=False)),
                ('supprime', models.BooleanField(default=False)),
                ('date_synchronisation', models.DateTimeField(blank=True, null=True)),
                ('appareil', models.CharField(blank=True, max_length=150)),
                ('table', models.CharField(max_length=100)),
                ('enregistrement_id', models.UUIDField()),
                ('action', models.CharField(choices=[('cree', 'Créé'), ('modifie', 'Modifié'), ('supprime', 'Supprimé')], max_length=15)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('synchronise', 'Synchronisé'), ('conflit', 'Conflit')], default='en_attente', max_length=15)),
                ('donnees', models.JSONField(blank=True, default=dict)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journaux_sync', to='comptes.boutique')),
            ],
            options={
                'ordering': ['-date_creation'],
                'abstract': False,
            },
        ),
    ]
