# Generated by Django 5.2.16 on 2026-07-26 17:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('synchronise', models.BooleanField(default=False)),
                ('supprime', models.BooleanField(default=False)),
                ('date_synchronisation', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('rappel_credit', 'Rappel de crédit'), ('alerte_rupture', 'Alerte de rupture'), ('ticket_whatsapp', 'Ticket WhatsApp')], max_length=20)),
                ('canal', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('interne', "Interne (dans l'appli)")], default='interne', max_length=15)),
                ('destinataire', models.CharField(blank=True, max_length=150)),
                ('message', models.TextField()),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('envoyee', 'Envoyée'), ('echouee', 'Échouée')], default='en_attente', max_length=15)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='comptes.boutique')),
            ],
            options={
                'ordering': ['-date_creation'],
                'abstract': False,
            },
        ),
    ]
