# Generated by Django 5.2.16 on 2026-07-31 11:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0004_demandeinscription_and_more'),
        ('notifications', '0002_notification_depot_notification_utilisateur'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='canal',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='date_envoi',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='destinataire',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='utilisateur',
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('alerte_rupture', 'Alerte de rupture')], default='alerte_rupture', max_length=20),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('synchronise', models.BooleanField(default=False)),
                ('supprime', models.BooleanField(default=False)),
                ('date_synchronisation', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('rappel_credit', 'Rappel de crédit'), ('ticket_whatsapp', 'Ticket WhatsApp')], max_length=20)),
                ('canal', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('interne', 'Interne (pas de téléphone connu, à traiter manuellement)')], default='interne', max_length=15)),
                ('destinataire', models.CharField(blank=True, max_length=150)),
                ('message', models.TextField()),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('envoyee', 'Envoyée'), ('echouee', 'Échouée')], default='en_attente', max_length=15)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='comptes.boutique')),
                ('depot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='stock.depot')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
                'abstract': False,
            },
        ),
    ]
