# Generated by Django 5.2.16 on 2026-09-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_remove_notification_canal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('alerte_rupture', 'Alerte de rupture'), ('alerte_dormants', 'Produits dormants'), ('fin_destockage', "Fin prochaine d'un déstockage")], default='alerte_rupture', max_length=20),
        ),
    ]
