# Generated by Django 5.2.16 on 2026-09-27 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_types_alertes_destockage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('alerte_rupture', 'Alerte de rupture'), ('alerte_dormants', 'Produits dormants'), ('fin_destockage', "Fin prochaine d'un déstockage"), ('echeance_proche', 'Échéance de dette fournisseur proche'), ('echeance_retard', 'Échéance de dette fournisseur en retard')], default='alerte_rupture', max_length=20),
        ),
    ]
