# Generated by Django 5.2.16 on 2026-08-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tresorerie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementcaisse',
            name='categorie',
            field=models.CharField(choices=[('vente_especes', 'Vente en espèces'), ('remboursement_credit', 'Remboursement crédit client'), ('transfert_mobile_money', 'Transfert mobile money'), ('apport', 'Mise de fonds'), ('depense', 'Dépense'), ('retrait', 'Retrait'), ('paiement_dette_fournisseur', 'Paiement dette fournisseur'), ('ajustement', 'Ajustement')], max_length=30),
        ),
    ]
