# Generated by Django 5.2.16 on 2026-09-30 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tresorerie', '0004_alter_mouvementcaisse_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementcaisse',
            name='categorie',
            field=models.CharField(choices=[('vente_especes', 'Vente en espèces'), ('remboursement_credit', 'Règlement crédit client'), ('transfert_mobile_money', 'Transfert mobile money'), ('apport', 'Mise de fonds'), ('depense', 'Dépense'), ('retrait', 'Retrait'), ('paiement_dette_fournisseur', 'Paiement dette fournisseur'), ('paiement_fournisseur', 'Paiement fournisseur (réception)'), ('depot_client', 'Dépôt sur compte client'), ('rendu_client', 'Argent rendu à un client'), ('avance_fournisseur', 'Avance à un fournisseur'), ('remboursement_fournisseur', "Remboursement d'un fournisseur"), ('ajustement', 'Ajustement')], max_length=30),
        ),
    ]
